:encoding: utf-8
:lang: es
:toc: right
:toc-title: Tabla de contenidos
:doctype: book
:imagesdir: ./images
:table-caption: Tabla
:example-caption: Ejemplo
:figure-caption: Figura
:linkattrs:

# Primeros pasos en OpenStack-STIC

Para utilizar OpenStack-STIC es necesario disponer de una cuenta de usuario. El acceso sólo está permitido desde la red de la UAL. El acceso desde fuera de la UAL se realizará mediante VPN.

## Solicitud de cuenta de usuario

. Solicita mediante https://caustic.ual.es/[CAU] el acceso a OpenStack-STIC. Te proporcionarán un dominio, un login y un password de acceso.

. Introduce tus credenciales en https://openstack.stic.ual.es/horizon[OpenStack-STIC]. Una vez dentro del sistema tendrás acceso a un *proyecto* OpenStack.

[NOTE]
====
Un proyecto OpenStack es un conjunto de recursos disponible para uno o más usuarios. Ejemplos de recursos básicos son los núcleos de procesador (VCPU), RAM o espacio de almacenamiento.

De forma predeterminada cada usuario tiene un proyecto. No obstante, un mismo usuario puede ser miembro de más de un proyecto (p.e. _Aulas, Servidores de Logs_)
====

## Cambio de la contraseña

Para cambiar la clave proporcionada, despliega el menú de las opciones del usuario conectado situado en la parte superior derecha y selecciona `Settings`
.
Settings.png

Se desplegará un menú en la izquierda. A continuación, selecciona Change password.

Servicios que ofrece OpenStack-STIC

OpenStack-STIC es el proyecto de Cloud-STIC que ofrece Infraestructura como servicio. Pese a ser el proyecto de base sobre el que se sustenta el cloud del STIC, lo consideramos como un componente más.

Actualmente, OpenStack-STIC ofrece:

Servicios para la creación de Máquinas y Aulas virtuales.

Servicios de Almacenamiento, tanto de bloques como volúmenes NFS.

Balanceadores como servicio.

OpenStack-STIC es OpenStack Stein e incluye los componentes:

Keystone: Identificación

Glance: Imágenes

Nova: Cómputo

Placement: Reserva y gestión de recursos

Neutron: Networking

Neutron Load Balancer: Balanceadores

Horizon: Interfaz web

Cinder: Almacenamiento de bloques

Manila: Almacenamiento compartido


[quote,AsciiDoc Syntax Quick Reference]
____
AsciiDoc is a lightweight markup language for authoring notes, articles, documentation, books, web pages, slide decks and man pages in plain text. This guide is a quick reference for the common AsciiDoc document and text formatting markup.
____

.Código de ejemplo para aprovisionar una instancia
****
```bash
#!/bin/bash

echo "Instalando Docker" <1>

apt-get update
apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io
groupadd docker
usermod -aG docker ubuntu
systemctl enable docker

echo "Instalando Docker Compose" <2>
curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```
<1> Mensaje de instalación de Docker
<2> Mensaje de instalación de Docker Compose
****

<<Solicitud de cuenta de usuario>>
